[package]
name = "kwaymerge"
version = "0.1.0"
authors = ["lakwet <axelle.piot@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.4.0"

[dev-dependencies]
rand = "0.7.3"
